apiVersion: v1
kind: Namespace
metadata:
  name: pheme
  labels:
    name: pheme
---
apiVersion: v1
kind: Service
metadata:
  name: pheme
  namespace: pheme
spec:
  type: LoadBalancer
  ports:
    - port: 8888
  selector:
    app: pheme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pheme
  namespace: pheme
  labels:
    app: pheme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pheme
  template:
    metadata:
      labels:
        app: pheme
    spec:
      containers:
        - name: pheme
          image: anthonyshull/pheme
          ports:
            - containerPort: 8888
              name: pheme
              protocol: TCP
